#!/usr/bin/env tsx
/**
 * Expose local API (3100) + web (3000) via Cloudflare quick tunnels for ChatGPT MCP testing.
 *
 * Usage: pnpm mcp:tunnel
 * Requires: API and web dev servers already running locally.
 */
import { spawn } from "node:child_process";
import { chmodSync, createWriteStream, existsSync, mkdirSync } from "node:fs";
import { pipeline } from "node:stream/promises";
import { finished } from "node:stream/promises";
import { resolve } from "node:path";
import { get as httpGet } from "node:http";

const ROOT = resolve(import.meta.dirname, "..");
const BIN_DIR = resolve(ROOT, ".bin");
const CLOUDFLARED = resolve(BIN_DIR, process.platform === "win32" ? "cloudflared.exe" : "cloudflared");
const CLOUDFLARED_URL =
  process.arch === "arm64"
    ? "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
    : "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64";

async function waitForPort(port: number, label: string, timeoutMs = 15_000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      await new Promise<void>((resolve, reject) => {
        const req = httpGet(`http://127.0.0.1:${port}/`, (res) => {
          res.resume();
          resolve();
        });
        req.on("error", reject);
        req.setTimeout(2000, () => {
          req.destroy();
          reject(new Error("timeout"));
        });
      });
      return;
    } catch {
      await sleep(500);
    }
  }
  throw new Error(`${label} is not responding on port ${port}. Start dev servers first.`);
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function downloadCloudflared(): Promise<string> {
  if (existsSync(CLOUDFLARED)) return CLOUDFLARED;
  mkdirSync(BIN_DIR, { recursive: true });
  console.log("Downloading cloudflared (one-time)…");
  const res = await fetch(CLOUDFLARED_URL);
  if (!res.ok || !res.body) throw new Error(`Failed to download cloudflared: ${res.status}`);
  await pipeline(res.body as unknown as NodeJS.ReadableStream, createWriteStream(CLOUDFLARED));
  chmodSync(CLOUDFLARED, 0o755);
  return CLOUDFLARED;
}

async function resolveCloudflared(): Promise<string> {
  if (existsSync(CLOUDFLARED)) return CLOUDFLARED;
  return downloadCloudflared();
}

function parseTunnelUrl(line: string): string | null {
  const m = line.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/i);
  return m?.[0] ?? null;
}

async function startTunnel(
  bin: string,
  port: number,
  label: string,
): Promise<{ url: string; proc: ReturnType<typeof spawn> }> {
  const proc = spawn(bin, ["tunnel", "--url", `http://127.0.0.1:${port}`, "--no-autoupdate"], {
    stdio: ["ignore", "pipe", "pipe"],
  });

  const url = await new Promise<string>((resolvePromise, reject) => {
    const timeout = setTimeout(() => reject(new Error(`${label} tunnel timed out`)), 45_000);
    const tryLine = (line: string) => {
      const u = parseTunnelUrl(line);
      if (u) {
        clearTimeout(timeout);
        resolvePromise(u);
      }
    };
    proc.stdout?.on("data", (buf: Buffer) => {
      const text = buf.toString();
      process.stderr.write(`[${label}] ${text}`);
      for (const line of text.split("\n")) tryLine(line);
    });
    proc.stderr?.on("data", (buf: Buffer) => {
      const text = buf.toString();
      process.stderr.write(`[${label}] ${text}`);
      for (const line of text.split("\n")) tryLine(line);
    });
    proc.on("error", (err) => {
      clearTimeout(timeout);
      reject(err);
    });
    proc.on("exit", (code) => {
      if (code !== 0 && code !== null) {
        clearTimeout(timeout);
        reject(new Error(`${label} tunnel exited with code ${code}`));
      }
    });
  });

  console.log(`\n✓ ${label} tunnel: ${url}  →  localhost:${port}\n`);
  return { url, proc };
}

async function writeEnvTunnel(apiUrl: string, webUrl: string) {
  const { writeFileSync } = await import("node:fs");
  const path = resolve(ROOT, ".env.tunnel");
  const cors = ["http://localhost:3000", webUrl].join(",");
  const content = `# Auto-generated by pnpm mcp:tunnel — restart API with these values
PUBLIC_API_URL=${apiUrl}
WEB_APP_URL=${webUrl}
CORS_ORIGINS=${cors}
NEXT_PUBLIC_API_URL=${apiUrl}
`;
  writeFileSync(path, content, "utf8");
  console.log(`Wrote ${path}\n`);
}

function printInstructions(apiUrl: string, webUrl: string) {
  const mcpUrl = `${apiUrl}/mcp`;
  const metaUrl = `${apiUrl}/.well-known/oauth-authorization-server`;

  console.log("═══════════════════════════════════════════════════════════");
  console.log(" ChatGPT MCP — local tunnel ready");
  console.log("═══════════════════════════════════════════════════════════");
  console.log("");
  console.log("1) Restart API + web so OAuth URLs use the tunnel:");
  console.log("   dotenv -e .env -e .env.tunnel -o -- pnpm --filter @quickstart-ai/api dev");
  console.log("   dotenv -e .env -e .env.tunnel -o -- pnpm --filter @quickstart-ai/web dev");
  console.log("");
  console.log("2) In ChatGPT → Settings → Connectors → Add MCP server:");
  console.log(`   URL: ${mcpUrl}`);
  console.log("");
  console.log("3) Complete OAuth when prompted (consent opens at your tunneled web URL).");
  console.log("");
  console.log("Quick checks:");
  console.log(`   curl ${metaUrl}`);
  console.log(`   pnpm mcp:test ${apiUrl}`);
  console.log("");
  console.log("Press Ctrl+C to stop tunnels.");
  console.log("═══════════════════════════════════════════════════════════\n");
}

async function main() {
  console.log("Checking local services…");
  await waitForPort(3100, "API");
  await waitForPort(3000, "Web");

  const bin = await resolveCloudflared();
  console.log(`Using cloudflared: ${bin}\n`);

  const api = await startTunnel(bin, 3100, "API");
  const web = await startTunnel(bin, 3000, "Web");

  await writeEnvTunnel(api.url, web.url);
  printInstructions(api.url, web.url);

  const shutdown = () => {
    api.proc.kill("SIGTERM");
    web.proc.kill("SIGTERM");
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  await Promise.all([
    api.proc.stdout ? finished(api.proc.stdout) : Promise.resolve(),
    web.proc.stdout ? finished(web.proc.stdout) : Promise.resolve(),
  ]).catch(() => undefined);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
